# Generated by Django 5.2.4 on 2025-08-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notebook_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='story',
            field=models.TextField(blank=True, help_text='Enter the story or notes of the notebook'),
        ),
    ]
