# Generated by Django 5.2.4 on 2025-08-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_notebook_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='notebook',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='story',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
