# Generated by Django 5.2.4 on 2025-08-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_notebook_author_notebook_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='notebook_images/'),
        ),
    ]
