# Generated by Django 5.2.4 on 2025-08-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_notebook_cover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
